# Generated by Django 4.2.15 on 2025-03-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0013_alter_weatherstation_concelho"),
        ("wildfires", "0002_remove_wildfire_created_at_remove_wildfire_local_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyWildfireSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                ("total_fires", models.IntegerField(verbose_name="Total Fires")),
                (
                    "total_area_ha",
                    models.FloatField(verbose_name="Total Burned Area (ha)"),
                ),
                (
                    "forest_area_ha",
                    models.FloatField(verbose_name="Forest Area Burned (ha)"),
                ),
                (
                    "shrub_area_ha",
                    models.FloatField(verbose_name="Shrubland Area Burned (ha)"),
                ),
                (
                    "agric_area_ha",
                    models.FloatField(verbose_name="Agricultural Area Burned (ha)"),
                ),
                (
                    "avg_duration_hours",
                    models.FloatField(verbose_name="Average Fire Duration (hours)"),
                ),
                (
                    "fires_over_24h",
                    models.IntegerField(verbose_name="Fires Lasting Over 24 Hours"),
                ),
                (
                    "max_fire_size_ha",
                    models.FloatField(verbose_name="Maximum Fire Size (ha)"),
                ),
                (
                    "concelho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_wildfire_summaries",
                        to="location.concelho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yearly Wildfire Summary",
                "verbose_name_plural": "Yearly Wildfire Summaries",
                "ordering": ["-year", "concelho"],
                "indexes": [
                    models.Index(fields=["year"], name="wildfires_y_year_069b2d_idx"),
                    models.Index(
                        fields=["concelho"], name="wildfires_y_concelh_7f79f1_idx"
                    ),
                ],
                "unique_together": {("year", "concelho")},
            },
        ),
    ]
