# Generated by Django 4.2.15 on 2025-03-17 11:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0013_alter_weatherstation_concelho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wildfire",
            fields=[
                (
                    "codigo_sgif",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="SGIF Code",
                    ),
                ),
                (
                    "codigo_anepc",
                    models.FloatField(blank=True, null=True, verbose_name="ANEPC Code"),
                ),
                (
                    "data_hora_alerta",
                    models.DateTimeField(verbose_name="Alert Date/Time"),
                ),
                (
                    "data_hora_extincao",
                    models.DateTimeField(verbose_name="Extinction Date/Time"),
                ),
                ("duracao_horas", models.FloatField(verbose_name="Duration (Hours)")),
                (
                    "inc_sup_24horas",
                    models.BooleanField(
                        default=False, verbose_name="Incident > 24 Hours"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326, verbose_name="Location"
                    ),
                ),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                (
                    "local",
                    models.CharField(max_length=255, verbose_name="Location Name"),
                ),
                ("ano", models.IntegerField(verbose_name="Year")),
                ("mes", models.IntegerField(verbose_name="Month")),
                ("dia", models.IntegerField(verbose_name="Day")),
                ("hora", models.IntegerField(verbose_name="Hour")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concelho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wildfires",
                        to="location.concelho",
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wildfires",
                        to="location.distrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wildfire",
                "verbose_name_plural": "Wildfires",
                "ordering": ["-data_hora_alerta"],
                "indexes": [
                    models.Index(
                        fields=["ano", "mes"], name="wildfires_w_ano_8f427d_idx"
                    ),
                    models.Index(
                        fields=["concelho"], name="wildfires_w_concelh_63b2b3_idx"
                    ),
                    models.Index(
                        fields=["distrito"], name="wildfires_w_distrit_3ba1ea_idx"
                    ),
                ],
            },
        ),
    ]
