# Generated by Django 4.2.15 on 2025-03-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wildfires", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wildfire",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wildfire",
            name="local",
        ),
        migrations.RemoveField(
            model_name="wildfire",
            name="location",
        ),
        migrations.RemoveField(
            model_name="wildfire",
            name="updated_at",
        ),
    ]
