# Generated by Django 4.2.15 on 2024-09-14 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_rename_name_sensorlocation_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorlocation",
            name="sensor_id",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Sensor ID must be an 8-digit number."
                    )
                ],
            ),
        ),
    ]
