# Generated by Django 4.2.15 on 2025-02-14 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0008_alter_city_globalidlocal_alter_concelho_idconcelho_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concelho",
            options={"ordering": ["dico_code"]},
        ),
        migrations.AlterModelOptions(
            name="distrito",
            options={"ordering": ["district_code"]},
        ),
        migrations.RemoveField(
            model_name="city",
            name="globalIdLocal",
        ),
        migrations.RemoveField(
            model_name="country",
            name="id",
        ),
        migrations.RemoveField(
            model_name="distrito",
            name="id",
        ),
        migrations.RemoveField(
            model_name="distrito",
            name="idDistrito",
        ),
        migrations.RemoveField(
            model_name="distrito",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="idRegiao",
        ),
        migrations.AddField(
            model_name="city",
            name="global_id",
            field=models.CharField(
                default=1,
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    django.core.validators.MaxLengthValidator(7),
                ],
                verbose_name="IPMA Global ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="ipma_area_code",
            field=models.CharField(
                default=1,
                max_length=3,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(3),
                ],
                verbose_name="IPMA Area Code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="concelho",
            name="concelho_code",
            field=models.CharField(
                default=1,
                max_length=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
                verbose_name="Municipality Code (DICO part 2)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="concelho",
            name="dico_code",
            field=models.CharField(
                default=1,
                help_text="Full DICO code (District + Municipality)",
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(4),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distrito",
            name="district_code",
            field=models.CharField(
                default=1,
                max_length=2,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
                verbose_name="District Code (DICO part 1)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="region_code",
            field=models.IntegerField(
                choices=[
                    (1, "Mainland Portugal"),
                    (2, "Madeira Archipelago"),
                    (3, "Azores Archipelago"),
                ],
                default=1,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                max_length=3,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="location.country"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="concelho",
            unique_together={("distrito", "concelho_code")},
        ),
        migrations.RemoveField(
            model_name="concelho",
            name="idConcelho",
        ),
    ]
