# Generated by Django 4.2.15 on 2025-02-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0009_alter_concelho_options_alter_distrito_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="concelho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="location.concelho",
                to_field="dico_code",
            ),
        ),
    ]
