# Generated by Django 4.2.15 on 2025-02-17 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0010_alter_city_concelho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherstation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="weatherstation",
            name="longitude",
        ),
        migrations.AddField(
            model_name="weatherstation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
