# Generated by Django 4.2.15 on 2025-02-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0011_remove_weatherstation_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherstation",
            options={"ordering": ["concelho", "name"]},
        ),
        migrations.RemoveField(
            model_name="weatherstation",
            name="city",
        ),
        migrations.AddField(
            model_name="weatherstation",
            name="concelho",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_stations",
                to="location.concelho",
                verbose_name="Municipality",
            ),
            preserve_default=False,
        ),
    ]
