# Generated by Django 4.2.15 on 2025-02-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0012_alter_weatherstation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstation",
            name="concelho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_stations",
                to="location.concelho",
                to_field="dico_code",
                verbose_name="Municipality",
            ),
        ),
    ]
