# Generated by Django 4.2.17 on 2025-06-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_weatherstation_concelho'),
    ]

    operations = [
        migrations.AddField(
            model_name='concelho',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Area of the concelho in hectares', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ConcelhoLandOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Date for which this land occupation data applies')),
                ('territorios_artificializados', models.DecimalField(decimal_places=4, help_text='Percentage of artificalized territories', max_digits=8)),
                ('pastagens', models.DecimalField(decimal_places=4, help_text='Percentage of pastures', max_digits=8)),
                ('florestas', models.DecimalField(decimal_places=4, help_text='Percentage of forests', max_digits=8)),
                ('massas_agua_superficiais', models.DecimalField(decimal_places=4, help_text='Percentage of surface water bodies', max_digits=8)),
                ('matos', models.DecimalField(decimal_places=4, help_text='Percentage of scrubland/bushes', max_digits=8)),
                ('superficies_agroflorestais', models.DecimalField(decimal_places=4, help_text='Percentage of agroforestry surfaces (SAF)', max_digits=8)),
                ('espacos_descobertos_pouca_vegetacao', models.DecimalField(decimal_places=4, help_text='Percentage of bare ground or sparse vegetation', max_digits=8)),
                ('agricultura', models.DecimalField(decimal_places=4, help_text='Percentage of agriculture', max_digits=8)),
                ('zonas_humidas', models.DecimalField(decimal_places=4, help_text='Percentage of wetlands', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_occupation', to='location.concelho', to_field='dico_code')),
            ],
            options={
                'verbose_name': 'Concelho Land Occupation',
                'verbose_name_plural': 'Concelho Land Occupations',
                'ordering': ['-reference_date', 'concelho'],
                'indexes': [models.Index(fields=['reference_date'], name='location_co_referen_ce14ed_idx'), models.Index(fields=['concelho', 'reference_date'], name='location_co_concelh_93def2_idx')],
                'unique_together': {('concelho', 'reference_date')},
            },
        ),
    ]
