# Generated by Django 4.2.17 on 2025-06-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_concelho_area_ha_concelholandoccupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concelho',
            name='area_ha',
        ),
        migrations.AddField(
            model_name='concelholandoccupation',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Area of the concelho in hectares', max_digits=12, null=True),
        ),
    ]
