# Generated by Django 4.2.17 on 2025-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_remove_concelho_area_ha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concelholandoccupation',
            options={'ordering': ['concelho'], 'verbose_name': 'Concelho Land Occupation', 'verbose_name_plural': 'Concelho Land Occupations'},
        ),
        migrations.RemoveIndex(
            model_name='concelholandoccupation',
            name='location_co_referen_ce14ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='concelholandoccupation',
            name='location_co_concelh_93def2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='concelholandoccupation',
            unique_together={('concelho',)},
        ),
        migrations.AlterField(
            model_name='concelholandoccupation',
            name='area_ha',
            field=models.DecimalField(decimal_places=4, help_text='Area of the concelho in hectares', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='concelholandoccupation',
            index=models.Index(fields=['concelho'], name='location_co_concelh_bd7cfb_idx'),
        ),
        migrations.RemoveField(
            model_name='concelholandoccupation',
            name='reference_date',
        ),
    ]
