# Generated by Django 4.2.17 on 2025-06-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_alter_concelholandoccupation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concelholandoccupation',
            name='concelho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_occupation', to='location.concelho'),
        ),
    ]
