# Generated by Django 4.2.15 on 2024-08-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_customuser_organization"),
        ("data_source", "0002_sensorlocation_remove_sensorstatus_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorlocation",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_locations",
                to="accounts.organization",
            ),
        ),
    ]
