# Generated by Django 4.2.15 on 2024-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_alter_sensorinfo_manufacturer_alter_sensorinfo_model"),
        ("data_source", "0004_rename_sensordata_sensordatadummy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("data_update", models.DateTimeField()),
                ("id_weather_type", models.IntegerField()),
                (
                    "temperature_min",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "temperature_max",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "precipitation_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("predominant_wind_direction", models.CharField(max_length=2)),
                ("wind_speed_class", models.IntegerField()),
                (
                    "precipitation_intensity_class",
                    models.IntegerField(blank=True, null=True),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="location.distrito",
                    ),
                ),
            ],
        ),
    ]
