# Generated by Django 4.2.15 on 2025-03-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0003_weatherwarning_city"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="firerisk",
            unique_together=set(),
        ),
    ]
