# Generated by Django 4.2.17 on 2025-06-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0014_concelho_area_ha_concelholandoccupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcelhoRiskAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(help_text='Date for which this risk analysis applies')),
                ('risk_mean', models.DecimalField(decimal_places=4, help_text='Mean risk value', max_digits=8)),
                ('risk_median', models.IntegerField(help_text='Median risk value')),
                ('risk_minority', models.IntegerField(help_text='Minority risk value')),
                ('risk_majority', models.IntegerField(help_text='Majority risk value')),
                ('analysis_period_start', models.DateField(blank=True, help_text='Start date of the period used for risk analysis', null=True)),
                ('analysis_period_end', models.DateField(blank=True, help_text='End date of the period used for risk analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analytics', to='location.concelho', to_field='dico_code')),
            ],
            options={
                'verbose_name': 'Concelho Risk Analytics',
                'verbose_name_plural': 'Concelho Risk Analytics',
                'ordering': ['-analysis_date', 'concelho'],
                'indexes': [models.Index(fields=['analysis_date'], name='analytics_c_analysi_b4c1bc_idx'), models.Index(fields=['concelho', 'analysis_date'], name='analytics_c_concelh_4936a1_idx'), models.Index(fields=['risk_mean'], name='analytics_c_risk_me_cdf6b2_idx')],
                'unique_together': {('concelho', 'analysis_date')},
            },
        ),
    ]
