# Generated by Django 4.2.17 on 2025-06-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_concelholandoccupation_concelho'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concelhoriskanalytics',
            name='concelho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analytics', to='location.concelho'),
        ),
    ]
