# Generated by Django 4.2.17 on 2025-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_concelholandoccupation_concelho'),
        ('analytics', '0002_alter_concelhoriskanalytics_concelho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concelhoriskanalytics',
            options={'ordering': ['concelho'], 'verbose_name': 'Concelho Risk Analytics', 'verbose_name_plural': 'Concelho Risk Analytics'},
        ),
        migrations.RemoveIndex(
            model_name='concelhoriskanalytics',
            name='analytics_c_analysi_b4c1bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='concelhoriskanalytics',
            name='analytics_c_concelh_4936a1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='concelhoriskanalytics',
            unique_together={('concelho',)},
        ),
        migrations.AddIndex(
            model_name='concelhoriskanalytics',
            index=models.Index(fields=['concelho'], name='analytics_c_concelh_bca6ed_idx'),
        ),
        migrations.RemoveField(
            model_name='concelhoriskanalytics',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='concelhoriskanalytics',
            name='analysis_period_end',
        ),
        migrations.RemoveField(
            model_name='concelhoriskanalytics',
            name='analysis_period_start',
        ),
    ]
