# Generated by Django 4.2.17 on 2025-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_concelholandoccupation_concelho'),
        ('analytics', '0004_concelhowildfirerecovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concelhowildfirerecovery',
            options={'ordering': ['-data_date', 'concelho'], 'verbose_name': 'Concelho Wildfire Recovery', 'verbose_name_plural': 'Concelho Wildfire Recovery'},
        ),
        migrations.RemoveIndex(
            model_name='concelhowildfirerecovery',
            name='analytics_c_analysi_347ffa_idx',
        ),
        migrations.RemoveIndex(
            model_name='concelhowildfirerecovery',
            name='analytics_c_concelh_bacf96_idx',
        ),
        migrations.RemoveIndex(
            model_name='concelhowildfirerecovery',
            name='analytics_c_wildfir_b01c9b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='concelhowildfirerecovery',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='concelhowildfirerecovery',
            name='data_date',
            field=models.DateField(default='2024-01-01', help_text='Date for this recovery data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concelhowildfirerecovery',
            name='significant_burn_recovery',
            field=models.IntegerField(choices=[(0, 'No significant burn recovery'), (1, 'Significant burn recovery')], help_text='Indicator if region had significant wildfire recovery (0 or 1)'),
        ),
        migrations.AlterUniqueTogether(
            name='concelhowildfirerecovery',
            unique_together={('concelho', 'data_date')},
        ),
        migrations.AddIndex(
            model_name='concelhowildfirerecovery',
            index=models.Index(fields=['data_date'], name='analytics_c_data_da_102afa_idx'),
        ),
        migrations.AddIndex(
            model_name='concelhowildfirerecovery',
            index=models.Index(fields=['concelho', 'data_date'], name='analytics_c_concelh_31af82_idx'),
        ),
        migrations.RemoveField(
            model_name='concelhowildfirerecovery',
            name='analysis_date',
        ),
        migrations.RemoveField(
            model_name='concelhowildfirerecovery',
            name='lookback_period_end',
        ),
        migrations.RemoveField(
            model_name='concelhowildfirerecovery',
            name='lookback_period_start',
        ),
        migrations.RemoveField(
            model_name='concelhowildfirerecovery',
            name='wildfire_season_year',
        ),
    ]
