# Generated by Django 4.2.15 on 2025-03-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0013_alter_weatherstation_concelho"),
        ("climate", "0002_firerisk"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherwarning",
            name="city",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"ipma_area_code__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weather_warnings",
                to="location.city",
            ),
        ),
    ]
