# Generated by Django 4.2.15 on 2025-03-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_weatherstation_concelho'),
        ('climate', '0004_alter_firerisk_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firerisk',
            unique_together={('concelho', 'forecast_day')},
        ),
    ]
