# Generated by Django 4.2.15 on 2025-04-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_alter_firerisk_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firerisk',
            unique_together=set(),
        ),
    ]
