# Generated by Django 4.2.15 on 2024-09-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_profile_picture"),
        ("data_source", "0004_rename_sensordata_sensordatadummy_and_more"),
        ("location", "0004_alter_sensorlocation_sensor_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SensorLocation",
            new_name="SensorInfo",
        ),
    ]
