# Generated by Django 4.2.15 on 2024-08-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_source", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sensorstatus",
            name="location",
        ),
        migrations.RemoveField(
            model_name="sensorstatus",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="sensorstatus",
            name="sensor_info",
        ),
        migrations.RemoveField(
            model_name="sensorstatus",
            name="user",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="SensorInfo",
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="data_source.sensorlocation",
            ),
        ),
        migrations.DeleteModel(
            name="SensorStatus",
        ),
    ]
