# Generated by Django 4.2.15 on 2024-09-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_coordinates_concelho_distrito_location_id_and_more"),
        ("data_source", "0003_sensorlocation_organization"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SensorData",
            new_name="SensorDataDummy",
        ),
        migrations.AlterField(
            model_name="sensordatadummy",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="location.sensorlocation",
            ),
        ),
        migrations.DeleteModel(
            name="SensorLocation",
        ),
    ]
